### ISSUE TITLE
Code needs updates to work

### ISSUE THREAD

**Issue by samadsajanlal** [xebialabs-community/slack-xlrelease-app#1]
We're trying to deploy this slack xlrelease app to test out its functionality.
It seems that the repository is unmaintained, as there are several things that have changed since the initial publication of this repo.

For one, the slack python API has changed to use a different library and various areas need to be updated. I've been able to perform this work and am happy to send a pull request with the changes.

However, getting past that, I now get errors like this when consul, vault, and redis are all operational (which did take extra steps due to permissions of the ./data directory, details that are not outlined in the readme). The vault is confirmed to be unsealed:

```./scripts/unseal.sh
[*] Config local environment...
[*] Unseal vault...
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.3.0
Cluster Name    vault-cluster-af01ba83
Cluster ID      2a0be90e-c036-76a6-d6b8-5a10ada0b3ea
HA Enabled      true
HA Cluster      https://consul:8301
HA Mode         active
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.3.0
Cluster Name    vault-cluster-af01ba83
Cluster ID      2a0be90e-c036-76a6-d6b8-5a10ada0b3ea
HA Enabled      true
HA Cluster      https://consul:8301
HA Mode         active
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.3.0
Cluster Name    vault-cluster-af01ba83
Cluster ID      2a0be90e-c036-76a6-d6b8-5a10ada0b3ea
HA Enabled      true
HA Cluster      https://consul:8301
HA Mode         active
```

500 error is thrown:

```slack-xlrelease-app    | 2020-01-02 20:31:19,133 - app - ERROR - Exception on /slack [POST]
slack-xlrelease-app    | Traceback (most recent call last):
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
slack-xlrelease-app    |     response = self.full_dispatch_request()
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/flask/app.py", line 1944, in full_dispatch_request
slack-xlrelease-app    |     self.try_trigger_before_first_request_functions()
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/flask/app.py", line 1992, in try_trigger_before_first_request_functions
slack-xlrelease-app    |     func()
slack-xlrelease-app    |   File "/opt/xebialabs/slack-xlrelease-app/app.py", line 105, in before_first_request
slack-xlrelease-app    |     xl_release_bot.recover_restart()
slack-xlrelease-app    |   File "/opt/xebialabs/slack-xlrelease-app/bot/xl_release_bot.py", line 223, in recover_restart
slack-xlrelease-app    |     access_token = self.vault_client.get_secret(path="access_token")
slack-xlrelease-app    |   File "/opt/xebialabs/slack-xlrelease-app/bot/db/vault_client.py", line 15, in get_secret
slack-xlrelease-app    |     record = self.vault_client.read("{}/{}".format(self.BASE_PATH, path))
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/hvac/v1/__init__.py", line 195, in read
slack-xlrelease-app    |     return self._adapter.get('/v1/{0}'.format(path), wrap_ttl=wrap_ttl).json()
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/hvac/adapters.py", line 90, in get
slack-xlrelease-app    |     return self.request('get', url, **kwargs)
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/hvac/adapters.py", line 272, in request
slack-xlrelease-app    |     utils.raise_for_error(response.status_code, text, errors=errors)
slack-xlrelease-app    |   File "/root/.local/share/virtualenvs/slack-xlrelease-app-8aDrVm-o/lib/python3.7/site-packages/hvac/utils.py", line 36, in raise_for_error
slack-xlrelease-app    |     raise exceptions.Forbidden(message, errors=errors)
slack-xlrelease-app    | hvac.exceptions.Forbidden: permission denied
```

This error occurs when attempting to enable events - Slack states the URL didn't respond with the challenge parameter, and the logs show that a 500 error is returned due to some permissions issue - but no details 

Any chance that this repository could get a maintenance update so that we can perform our analysis to see if this is a bot we want to build on?

**Comment by zvercodebender** [comment]
We just published a container image on docker hub that has been updated for the current version of the libs.

https://hub.docker.com/repository/docker/xebialabsunsupported/slack-xlrelease-app
